default: &default
  adapter: mysql2
  encoding: utf8
  username: root
  password: thants
  host: 127.0.0.1
  port: 3306

development:
  <<: *default
  database: my_database_tesing

# test:
#   <<: *default
#   database: test_db_name

# production:
#   <<: *default
#   database: production_db_name
